// <auto-generated />
using System;
using MedUnit.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MedUnit.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ContactMessage", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");
                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                b.Property<string>("Email").IsRequired().HasColumnType("text");
                b.Property<bool>("IsRead").HasColumnType("boolean");
                b.Property<string>("LastName").IsRequired().HasColumnType("text");
                b.Property<string>("Message").IsRequired().HasColumnType("text");
                b.Property<string>("Name").IsRequired().HasColumnType("text");
                b.Property<string>("Phone").IsRequired().HasColumnType("text");

                b.HasKey("Id");
                b.ToTable("ContactMessages");
            });

            modelBuilder.Entity("MedUnit.Domain.Entities.Klinik", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");
                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<string>("Ad").IsRequired().HasColumnType("text");
                b.Property<string>("Adres").HasColumnType("text");
                b.Property<string>("Telefon").HasColumnType("text");
                b.Property<string>("Email").HasColumnType("text");
                b.Property<string>("LogoUrl").HasColumnType("text");
                b.Property<string>("AbonelikTipi").IsRequired().HasColumnType("text");
                b.Property<DateTime?>("AbonelikBitisTarihi").HasColumnType("timestamp with time zone");
                b.Property<bool>("Aktif").HasColumnType("boolean");
                b.Property<DateTime>("OlusturulmaTarihi").HasColumnType("timestamp with time zone");

                b.HasKey("Id");
                b.ToTable("Klinikler");
            });

            modelBuilder.Entity("MedUnit.Domain.Entities.Kullanici", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");
                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<string>("Ad").IsRequired().HasColumnType("text");
                b.Property<bool>("Aktif").HasColumnType("boolean");
                b.Property<string>("Email")
                    .IsRequired()
                    .HasMaxLength(450)
                    .HasColumnType("character varying(450)");
                b.Property<int?>("KlinikId").HasColumnType("integer");
                b.Property<DateTime>("OlusturulmaTarihi").HasColumnType("timestamp with time zone");
                b.Property<string>("Rol")
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnType("character varying(20)");
                b.Property<string>("SifreHash").IsRequired().HasColumnType("text");
                b.Property<string>("SifreSifirlamaToken").HasColumnType("text");
                b.Property<DateTime?>("SifreSifirlamaTokenSon").HasColumnType("timestamp with time zone");
                b.Property<string>("Soyad").IsRequired().HasColumnType("text");
                b.Property<string>("Telefon")
                    .HasMaxLength(20)
                    .HasColumnType("character varying(20)");
                b.Property<string>("Uzmanlik")
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)");

                b.HasKey("Id");
                b.HasIndex("Email").IsUnique();
                b.HasIndex("KlinikId");
                b.ToTable("Kullanicilar");
            });

            modelBuilder.Entity("MedUnit.Domain.Entities.DoktorNotu", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");
                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<int>("RandevuId").HasColumnType("integer");
                b.Property<int>("DoktorId").HasColumnType("integer");
                b.Property<int>("HastaId").HasColumnType("integer");
                b.Property<string>("Not").IsRequired().HasColumnType("text");
                b.Property<string>("Tani").HasColumnType("text");
                b.Property<DateTime>("OlusturulmaTarihi").HasColumnType("timestamp with time zone");

                b.HasKey("Id");
                b.HasIndex("DoktorId");
                b.HasIndex("HastaId");
                b.HasIndex("RandevuId");
                b.ToTable("DoktorNotlari");
            });

            modelBuilder.Entity("MedUnit.Domain.Entities.TibbiDosya", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");
                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<int>("HastaId").HasColumnType("integer");
                b.Property<string>("DosyaAdi").IsRequired().HasColumnType("text");
                b.Property<string>("DosyaTipi").IsRequired().HasColumnType("text");
                b.Property<byte[]>("DosyaVerisi").IsRequired().HasColumnType("bytea");
                b.Property<long>("DosyaBoyutu").HasColumnType("bigint");
                b.Property<DateTime>("YuklemeTarihi").HasColumnType("timestamp with time zone");

                b.HasKey("Id");
                b.HasIndex("HastaId");
                b.ToTable("TibbiDosyalar");
            });

            modelBuilder.Entity("MedUnit.Domain.Entities.Randevu", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");
                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<DateTime>("BaslangicTarihi").HasColumnType("timestamp with time zone");
                b.Property<DateTime>("BitisTarihi").HasColumnType("timestamp with time zone");
                b.Property<int>("DoktorId").HasColumnType("integer");
                b.Property<string>("Durum").IsRequired().HasColumnType("text");
                b.Property<bool>("HatirlaticiGonderildi").HasColumnType("boolean");
                b.Property<int>("HastaId").HasColumnType("integer");
                b.Property<string>("Notlar").HasColumnType("text");
                b.Property<DateTime>("OlusturulmaTarihi").HasColumnType("timestamp with time zone");
                b.Property<string>("ZoomHostUrl").HasColumnType("text");
                b.Property<string>("ZoomJoinUrl").HasColumnType("text");
                b.Property<string>("ZoomMeetingId").HasColumnType("text");

                b.HasKey("Id");
                b.HasIndex("DoktorId");
                b.HasIndex("HastaId");
                b.ToTable("Randevular");
            });

            modelBuilder.Entity("MedUnit.Domain.Entities.Kullanici", b =>
            {
                b.HasOne("MedUnit.Domain.Entities.Klinik", "Klinik")
                    .WithMany()
                    .HasForeignKey("KlinikId")
                    .OnDelete(DeleteBehavior.SetNull);

                b.Navigation("Klinik");
            });

            modelBuilder.Entity("MedUnit.Domain.Entities.DoktorNotu", b =>
            {
                b.HasOne("MedUnit.Domain.Entities.Kullanici", "Doktor")
                    .WithMany()
                    .HasForeignKey("DoktorId")
                    .OnDelete(DeleteBehavior.NoAction)
                    .IsRequired();

                b.HasOne("MedUnit.Domain.Entities.Kullanici", "Hasta")
                    .WithMany()
                    .HasForeignKey("HastaId")
                    .OnDelete(DeleteBehavior.NoAction)
                    .IsRequired();

                b.HasOne("MedUnit.Domain.Entities.Randevu", "Randevu")
                    .WithMany()
                    .HasForeignKey("RandevuId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Doktor");
                b.Navigation("Hasta");
                b.Navigation("Randevu");
            });

            modelBuilder.Entity("MedUnit.Domain.Entities.TibbiDosya", b =>
            {
                b.HasOne("MedUnit.Domain.Entities.Kullanici", "Hasta")
                    .WithMany()
                    .HasForeignKey("HastaId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Hasta");
            });

            modelBuilder.Entity("MedUnit.Domain.Entities.Randevu", b =>
            {
                b.HasOne("MedUnit.Domain.Entities.Kullanici", "Doktor")
                    .WithMany()
                    .HasForeignKey("DoktorId")
                    .OnDelete(DeleteBehavior.NoAction)
                    .IsRequired();

                b.HasOne("MedUnit.Domain.Entities.Kullanici", "Hasta")
                    .WithMany()
                    .HasForeignKey("HastaId")
                    .OnDelete(DeleteBehavior.NoAction)
                    .IsRequired();

                b.Navigation("Doktor");
                b.Navigation("Hasta");
            });
#pragma warning restore 612, 618
        }
    }
}
